### PR TITLE
feat: multi arch and file-based OLM catalog

### PR DESCRIPTION
**Pull request by raelga**
- Updates all build targets with support for `arm64` and `amd64` images. 6b36cf9
- Adds the `catalog-*` targets to generate file-based OLM catalogs. 6b36cf9
- Adds the `release-catalog` GitHub workflow, to generate and build a catalog for the operator. 6b36cf9
- Generates the complete catalog with all bundle releases from [`v0.3.8`](https://github.com/external-secrets/external-secrets-helm-operator/releases/tag/v0.3.8) to [`v0.10.7`](https://github.com/external-secrets/external-secrets-helm-operator/releases/tag/v0.10.7). cf94821
- Updates the release documentation with the new targets. abbdada
- Removes the build step in the test workflow a3ac200

Related to:
- https://github.com/external-secrets/external-secrets/issues/3930
- https://olm.operatorframework.io/docs/reference/file-based-catalogs/

### CODE REVIEW

**Comment by Skarlso** [comment]
Hello. :) You have a test failure:

```
Error: must build at directory: not a valid directory: evalsymlink failure on 'config/testing' : lstat /home/runner/work/external-secrets-helm-operator/external-secrets-helm-operator/config/testing: no such file or directory
error: no objects passed to apply
```

**Comment by raelga** [comment]
@Skarlso It should be working now

**Comment by gusfcarvalho** [comment]
Hi @raelga . We internally have been discussing the feasibility of maintaining OLM releases within our team for a while now, and it is clear from past releases (https://github.com/external-secrets/external-secrets/issues/4036) we are not par to maintaining and further releasing OLM builds anymore.

On the community meeting today I have proposed https://github.com/external-secrets/external-secrets/pull/4175 and it was approved.

While this does not mean we are not having any support for OLM in the future, it is clear that a helm operator for OLM is not the way we want to go. As such, if we can find people to proper support an OLM operator for external-secrets, we will be more than happy to incorporate it again - as long as this is not a forcing function of the current release process.


As such, I am closing your contribution. Sorry about all of the fuss this might have caused 🙏 🙇

**Comment by raelga** [comment]
It's OK @gusfcarvalho, let us know if you need any help with the non-helm based operator. We are more than happy to help.

In the meantime, we are probably going to internally deprecate the usage of OLM operator and deploy directly with Helm.

**Pull request closed without merging**
